# Generated by Django 6.0.6 on 2026-06-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_priority_remove_task_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Niedrig'), ('medium', 'Mittel'), ('high', 'Hoch')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('To-do', 'Todo'), ('In-progress', 'In Bearbeitung'), ('Review', 'In Prüfung'), ('Done', 'Abgeschlossen')], default='To-do', max_length=20),
        ),
    ]
