# Generated by Django 6.0.6 on 2026-06-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_priority_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('To-do', 'To-do'), ('In-progress', 'In Bearbeitung'), ('Review', 'In Prüfung'), ('Done', 'Abgeschlossen')], default='To-do', max_length=20),
        ),
    ]
