# Generated by Django 6.0.6 on 2026-06-18 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_remove_task_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assignees',
            new_name='assignee',
        ),
    ]
